### ISSUE TITLE
xHyper-V - Fix issues flagged by scriptanalyzer

### ISSUE THREAD

**Issue by bgelens** [dsccommunity/xHyper-V#117]
* [x] xVHD
* [ ] xVhdFile
* [x] xVMHyperV

**Comment by bgelens** [comment]
xVHD will be fixed once #77 is merged

**Comment by bgelens** [comment]
xVhdFileDirectory will be fixed once #122 is merged

**Comment by bgelens** [comment]
xVMHyperV was fixed with #163

**Comment by johlju** [comment]
This is fixed with the conversion to new CI pipeline. There might still be things to do for HQRM level. But the flagged are fixed.
