### ISSUE TITLE
xVMNetworkAdapter: Setting Mac address raises exception:  "StaticMacAddress" is not in the correct format. 

### ISSUE THREAD

**Issue by pluggy** [dsccommunity/xHyper-V#172]
#### Details of the scenario you tried and the problem that is occurring
I am trying to set a mac address to a vm, but whatever I try I always get an exception stating that the mac address is malformed. Even if I am simply copying the mac address from your examples documentation page.

#### Verbose logs showing the problem
VERBOSE: Performing the operation "Start-DscConfiguration: SendMetaConfigurationApply" on target "MSFT_DSCLocalConfigurationManager".
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendMetaConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer HV2 with user sid S-1-5-21-533737547-3831762451-2231878310-500.
VERBOSE: [HV2]: LCM:  [ Start  Set      ]
VERBOSE: [HV2]: LCM:  [ Start  Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [HV2]: LCM:  [ Start  Set      ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [HV2]: LCM:  [ End    Set      ]  [MSFT_DSCMetaConfiguration]  in 0.0160 seconds.
VERBOSE: [HV2]: LCM:  [ End    Resource ]  [MSFT_DSCMetaConfiguration]
VERBOSE: [HV2]: LCM:  [ End    Set      ]
VERBOSE: [HV2]: LCM:  [ End    Set      ]    in  0.0620 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Set-DscLocalConfigurationManager finished in 0.601 seconds.
VERBOSE: Starting Configuration with the hv2.MOF file......
VERBOSE: Starting Configuration on remote host hv2 from MOF file path .\MOFFiles\TestConfiguration 
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer HV2 with user sid S-1-5-21-533737547-3831762451-2231878310-500.
VERBOSE: [HV2]: LCM:  [ Start  Set      ]
VERBOSE: [HV2]: LCM:  [ Start  Resource ]  [[cVMNetworkAdapter]AddWANNetworkAdapter]
VERBOSE: [HV2]: LCM:  [ Start  Test     ]  [[cVMNetworkAdapter]AddWANNetworkAdapter]
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] Getting VM Network Adapter information.
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] VM Network Adapter exists but without static MAC address setting.
VERBOSE: [HV2]: LCM:  [ End    Test     ]  [[cVMNetworkAdapter]AddWANNetworkAdapter]  in 0.1100 seconds.
VERBOSE: [HV2]: LCM:  [ Start  Set      ]  [[cVMNetworkAdapter]AddWANNetworkAdapter]
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] Getting VM Network Adapter information.
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] Found VM Network Adapter.
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] VM Network Adapter exists but without static MAC address setting.
VERBOSE: [HV2]:                            [[cVMNetworkAdapter]AddWANNetworkAdapter] Performing VM Network Adapter configuration changes.
VERBOSE: [HV2]: LCM:  [ End    Set      ]  [[cVMNetworkAdapter]AddWANNetworkAdapter]  in 0.1400 seconds.
PowerShell DSC resource cVMNetworkAdapter  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The parameter "StaticMacAddress" is not in the correct format. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : hv2
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
configuration TestConfiguration 
{
    

    Set-StrictMode -Version 3.0
    
    Import-DscResource -ModuleName  PSDesiredStateConfiguration -ModuleVersion 1.1
    Import-DscResource -ModuleName  cHyper-V
    

    node $AllNodes.NodeName 
    {
        
            
        LocalConfigurationManager {
            RebootNodeIfNeeded = $true
            ConfigurationMode  = 'ApplyAndMonitor'
            ActionAfterReboot  = 'ContinueConfiguration'
                
        }
        
         xVMNetworkAdapter AddWANNetworkAdapter {
        Id = 'WANNetworkAdapter'
        Name = 'WANNetworkAdapter'
        SwitchName = 'VMWANGateway'
        VMName = 'WB2'
         
        MacAddress = '001523be0c'
        
        Ensure = 'Present'
    

    }
}
}

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

3.16.0.0

**Comment by iainbrighton** [comment]
Hi @pluggy - it looks like your MAC address is 8 bits too short?! It needs to be `001523be0cXX`?

**Comment by pluggy** [comment]
Good point, I did not spot that when copying it from the documentation. Seems like I need a coffee. 

In this case, there are two typos in the examples section at [https://github.com/PowerShell/xHyper-V/blob/dev/Examples/Sample_xVMNetworkAdapter_MultipleVMMACAddress.ps1](https://github.com/PowerShell/xHyper-V/blob/dev/Examples/Sample_xVMNetworkAdapter_MultipleVMMACAddress.ps1)  since both mac addresses are too short.

**Comment by pluggy** [comment]
I reopened this so that the documentation can be fixed. Thanks for your help! :)
