### ISSUE TITLE
Examples require Hyper-V Feature

### ISSUE THREAD

**Issue by ericjaystevens** [dsccommunity/xHyper-V#54]
Examples in Examples\ require Hyper-V Feature. This prevents the examples from being run in Windows 10, or 8.1.

**Comment by iainbrighton** [comment]
@ericjaystevens Correct - the examples won't run on client OSes without some modifications. Are you suggesting that there needs to be documentation on how to run the examples on client OSes, that there are examples added for client OSes or that you need assistance getting them to run on a client OS?

**Comment by ericjaystevens** [comment]
@iainbrighton I think either separate examples should be provided for both sets of supported OSes, or some logic should be added to the examples to support both.

**Comment by aromano2** [comment]
closing stale issue
