### ISSUE TITLE
Error with incorrect property name is listed when user omits MaximumSizeBytes property of xVHD

### ISSUE THREAD

**Issue by neil-white-iHerb** [dsccommunity/xHyper-V#60]
When the user omits the "MaximumSizeBytes" property of the xVHD resource type (I might not have my terminology right), an error is thrown that gives the incorrect information:
PowerShell DSC resource MSFT_xVHD  failed to execute Test-TargetResource functionality with error message: Either specify ParentPath or MaximumSize property.

The messages should say "MaximumSizeBytes" property instead of "MaximumSize".
Nitpicky of me, but it might save some other newbies some time.

**Comment by aromano2** [comment]
resolved with #71
